LMS/urls.py
from django.contrib import admin
from django.urls import path,include
from lvids import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout',views.LogoutInterfaceView.as_view()),
    path('',include('lvids.urls')),
    path('',include('quiz.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lvids/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.Home.as_view(),name='home'),

    path('dep',views.Dep.as_view(),name='dep'),

    path('cse',views.Cse,name='cse'),

    path('login',views.LoginInterfaceView.as_view()),

    path('logout',views.LogoutInterfaceView.as_view()),

    path('signup',views.SignupView.as_view()),

    
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path('quiz/<int:pk>/', views.ExamDetailView.as_view(), name='exam'),
    #path('result',views.marks())
    ]

lvids/models.py
from django.db import models

# Create your models here.
class Video(models.Model):
    caption = models.CharField(max_length=100)
    video = models.FileField(upload_to="video/%y")
    def __str__(self):
        return self.caption

quiz/models.py
from django.db import models

# Create your models here.

class Exams(models.Model):
    exam_id=models.CharField(max_length=200)
    exam_name=models.CharField(max_length=200)



class Question(models.Model):
    exam = models.ForeignKey(Exams, on_delete=models.CASCADE)
    que_id=models.CharField(max_length=200)
    que_content=models.TextField()
    ansid=models.CharField(max_length=200)


class Answer(models.Model):
    que = models.ForeignKey(Question, on_delete=models.CASCADE)
    ans_content=models.CharField(max_length=200)
    ans_id=models.CharField(max_length=200)





lvids/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .models import Video
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
# Create your views here.
class SignupView(CreateView):
    form_class=UserCreationForm
    template_name='signup.html'
    success_url='/login'

class LogoutInterfaceView(LogoutView):
    template_name='lvids/logout.html'

class LoginInterfaceView(LoginView):
    template_name='login.html'


class Home(TemplateView):
    template_name='lvids/index.html'
    
class Dep(LoginRequiredMixin,TemplateView):
    template_name='dep.html'
    login_url='/login'
@login_required
def Cse(request):
    video = Video.objects.all()
    return render(request,'lvids/cse.html',{"video":video})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

quiz/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView,DetailView
from .models import Exams,Question,Answer
# Create your views here.


class ExamListView(ListView):
    model = Exams
    template_name = "quiz/index.html"
    context_object_name = 'exams'


class ExamDetailView(DetailView):
    model = Exams
    template_name = "quiz/quiz.html"
    context_object_name = 'exams'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = self.object.question_set.all()
        return context



lvids/templates/lvids/cse.html
{%extends "base.html"%}

{%block content%}
<div class="container">
    {%for x in video%}
    <h3 class="text-center mt-2 mb-2">{{x.caption}}</h3>
    <video width="600" height="400" controls ="controls">
        <source src="{{x.video.url}}" type="video/mp4"/>
    </video>
    <hr>
    {%endfor%}
</div>
{%endblock%}

lvids/templates/lvids/index.html

{%extends "base.html"%}
{%block content%}
<button class="toggle-btn2"><a href="signup">Sign Up</a></button>
<button class="toggle-btn1"><a href="login">Log In</a></button>
{%endblock%}

lvids/templates/lvids/logout.html
{%extends "base.html"%}
{%block content%}
<h2>You have been logged out.</h2>
{%endblock%}

quiz/templates/quiz/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

quiz/templates/quiz/quiz.html
{%load static%}
<html>
<head>
<title>Examination</title>
<link rel="stylesheet" href="{% static 'quiz/style.css' %}" type="text/css">
<script src="{% static 'quiz/script.js' %}"></script>
</head>
<body>
	<h1 id="head1">Quiz Time!</h1>
	<form >
	{%for x in question%}
		<label id="{{x.que_id}}"><h3>{{x.que_content}}</h3></label>
		<div class="opt">
		{%for y in x.answer_set.all%}
		<input type="checkbox" id="{{y.ans_id}}" value="{{y.ans_id}}">{{y.ans_content}}</input><hr>

		{%endfor%}
		</div>
	{%endfor%}
	<button type="button" id="sub">Submit</button>


	</form>
</body>
</html>